### ISSUE TITLE
Readme needs more detail: "Generator folder"

### ISSUE THREAD

**Issue by cdeadlock** [nbreum15/entitas-vs#2]
The readme says that you can use "The Normal Generator from Entitas" 

But what folder is that exactly?

**Comment by nbreum15** [comment]
Hi, and thanks for trying out the extension. After a new update Unity the Visual Studio Tools for Unity automatically add new items to Visual Studio that is added inside the Assets directory without showing the "Reload Solution" dialog (The Unity Tools also adds the items significantly faster than Entitas-vs). 

Therefore I recommend updating to the latest Visual Studio Tools for Unity and bind the code generation inside Visual Studio as described [here](https://github.com/sschmid/Entitas-CSharp/wiki/Code-generation-shortcut-for-Visual-Studio) and not use Entitas-vs as I won't be updating it anymore.

I will update the readme to accommodate this information.
